schema-version: 1.0
name: maven

volumes:
  - pom:"{{ pomdir }}":.
  - repo:/root/.m2:$HOME/.m2

var:
  version: "3.6.3"
  pomdir: /usr/src
  jdk: "8"
  mavenOptions:
  javaOptions:

dependencies:
  - name: aws-jdk
    model:
      version: "{{ jdk }}"
      javaOptions: "{{ javaOptions }}"

provision:
  - url: http://mirrors.standaloneinstaller.com/apache/maven/maven-3/{{ version }}/binaries/apache-maven-{{ version }}-bin.tar.gz
  - env: MAVEN_OPTS={{ mavenOptions }}
  - systempath: /opt/apache-maven-{{ version }}/bin

command:
  mvn:
    - shell:
        inline: mvn {{ .args }}
        directory: "{{ pomdir }}"
